meta_train_tasks:
- liar
- hatecheck
- tweet_eval
- sarcasm
- ob_gyn
- medicine
- pharmacology
- pathology
- logic_grid_puzzle
- tracking_shuffled_objects
- logical_deduction
- temporal_sequences
- beauty
- game
- baby
- office

meta_test_tasks:
- antropic_harmless
- ethos
- dental
- anatomy
- surgery
- pediatrics
- object_counting
- reasoning_colored_objects
- epistemic
- electronics
- pet
- sports
- natural_questions
- web_qa